### ISSUE TITLE
Fix rewrites

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMnetwork_admin#10]
Rewrites ved ny sesong feiler av ukjent grunn.
Dagens script for å håndtere det er nok mest sannsynlig ikke riktig (/blog/ blir med..?)
Analyser rewrite-rules og lag ny funksjon for dette

**Comment by mariusmandal** [comment]
Kan se ut til at WP nå håndterer dette riktig. 2017-sesongen i alle fall satt opp tilsynelatende uten feil

**Comment by AsgeirSH** [comment]
Rewrite for kommuner med fylkesnavn, eksempelvis Nes (Buskerud) bør endres fra /buskerud/nesbuskerud/ til /buskerud/nes/
- Nes (Akershus)
- Lærdal / Lardal (Works!)
- Os (Hordaland)
- Sande (Vestfold) / Sande (Møre og Romsdal)
- Grane (Nordland) / Gran (Oppland)
- Våler (Hedmark) / Våler (Hedmark) 

Grünerløkka blir fortsatt grnerlokka, fiks ü -> u i canonicalization-prosessen (For et ord! 😮  ).

Ellers funker det fint nå.

**Comment by mariusmandal** [comment]
Bare å kjøre en strpos og substr på ( så er den fixed.
Løkka er overraskende vanskelig faktisk.
