### ISSUE TITLE
Roller og rettigheter funker ikke

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMnetwork_admin#19]
Hva gjør menyen egentlig..?

**Comment by AsgeirSH** [comment]
Hvilken meny er det i det hele tatt snakk om...?

**Comment by mariusmandal** [comment]
lovely! ..skal sjekke :)

**Comment by mariusmandal** [comment]
http://ukm.no/wp-admin/network/admin.php?page=UKMA_roles_and_capabilities
